name: Pak's Secret
description: Blogging about IT stuffs
meta_description: "Software development"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl:
domain_name: 'http://paks.me'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://paks.me'
author:         'James Pak'
